version: "3"

services:
  database:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./config/db:/var/lib/postgresql/config/db
    container_name: roda_db

volumes:
  postgres-data:
