version: "2"
services:
  db:
    image: postgres
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: $${DATABASE_HOST}
      POSTGRES_PASSWORD: $${DATABASE_PASSWORD}
    ports:
      - 5431:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
