version: "2"
services:
  sqlserver:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DATABASE_PASSWORD}
      MSSQL_MEMORY_LIMIT_MB: 512m
    image: "microsoft/mssql-server-linux"
    ports:
      - ${DATABASE_PORT}:1433
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
