<%= ENV['RACK_ENV'] %>:
  adapter: tinytds
  mode: dblib
  timeout: 30
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  database: <%= ENV['DATABASE_DB'] %>
