<%= ENV['RACK_ENV'] %>: &default
  adapter: postgres
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_DB'] %>
  pool: 5
  timeout: 30
  max_connections: 5
