# frozen_string_literal: true

Beneficio.create(id: 10, nome: 'Assistência médica')
Beneficio.create(id: 20, nome: 'Assistência odontológica')
Beneficio.create(id: 30, nome: 'Auxílio academia')
Beneficio.create(id: 40, nome: 'Auxílio combustível')
Beneficio.create(id: 50, nome: 'Auxílio creche')
Beneficio.create(id: 60, nome: 'Auxílio desenvolvimento')
Beneficio.create(id: 70, nome: 'Auxílio estacionamento')
Beneficio.create(id: 80, nome: 'Auxílio farmácia')
Beneficio.create(id: 90, nome: 'Auxílio fretado')
Beneficio.create(id: 10, nome: 'Bicicletário')
Beneficio.create(id: 11, nome: 'Bolsa auxílio')
Beneficio.create(id: 12, nome: 'Café da manhã')
Beneficio.create(id: 13, nome: 'Cesta básica')
Beneficio.create(id: 14, nome: 'Cesta de natal')
Beneficio.create(id: 15, nome: 'Consignado')
Beneficio.create(id: 16, nome: 'Convênio com empresas parceiras')
Beneficio.create(id: 17, nome: 'Cooperativa de crédito')
Beneficio.create(id: 18, nome: 'Desconto em produtos')
Beneficio.create(id: 19, nome: 'Ginástica laboral')
Beneficio.create(id: 20, nome: 'Home office')
Beneficio.create(id: 21, nome: 'Horário flexível')
Beneficio.create(id: 22, nome: 'Massoterapia')
Beneficio.create(id: 23, nome: 'Participação nos Lucros ou Resultados')
Beneficio.create(id: 24, nome: 'Plano de Aquisição de Ações')
Beneficio.create(id: 25, nome: 'Previdência privada')
Beneficio.create(id: 27, nome: 'Programa de remuneração variável')
Beneficio.create(id: 28, nome: 'Programa de treinamentos')
Beneficio.create(id: 29, nome: 'Refeitório')
Beneficio.create(id: 30, nome: 'Restaurante interno')
Beneficio.create(id: 31, nome: 'Sala de Jogos')
Beneficio.create(id: 32, nome: 'Seguro de vida')
Beneficio.create(id: 33, nome: 'Vale alimentação')
Beneficio.create(id: 34, nome: 'Vale-cultura')
Beneficio.create(id: 35, nome: 'Vale-refeição')
Beneficio.create(id: 36, nome: 'Vale-transporte')
